try
{
const a=10
const b=2
var c=a/b
console.log(c)
}
catch(err)
{
    console.log(err.message)
}